# Generated by Django 3.1.13 on 2021-10-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playermat', '0001_squashed_0008_auto_20211002_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playermatresourcepeople',
            name='total',
        ),
    ]
