# Generated by Django 2.2.3 on 2019-11-30 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playermat', '0005_auto_20161009_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermat',
            name='barbarians',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('worker', 'worker')], max_length=12),
        ),
    ]
