# Generated by Django 3.1.13 on 2021-10-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playermat', '0006_auto_20191130_0425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='type',
            field=models.CharField(choices=[('guard', 'guard'), ('worker', 'worker'), ('barbarian', 'barbarian')], max_length=12),
        ),
    ]
