# Generated by Django 3.1.13 on 2021-10-03 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playermat', '0007_auto_20211002_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='iron',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='land',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='stone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(51, 'GUARD'), (50, 'WORKER')]),
        ),
        migrations.AlterField(
            model_name='playermatresourcepeople',
            name='wood',
            field=models.BooleanField(default=False),
        ),
    ]
