# Generated by Django 2.2.3 on 2019-08-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("game", "0003_auto_20160321_0414")]

    operations = [
        migrations.RenameField(
            model_name="game", old_name="choice_dice", new_name="dice_bank"
        ),
        migrations.RenameField(
            model_name="game", old_name="gather_dice", new_name="world_pool_dice"
        ),
    ]
