# Generated by Django 2.2.3 on 2019-11-28 20:30

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_auto_20190805_0448'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTurn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_no', models.PositiveSmallIntegerField(default=1)),
                ('first_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='game',
            old_name='dice_bank',
            new_name='choice_dice_bank',
        ),
        migrations.RemoveField(
            model_name='game',
            name='true_porkchop_used',
        ),
        migrations.RemoveField(
            model_name='game',
            name='world_pool_dice',
        ),
        migrations.AddField(
            model_name='game',
            name='gather_dice_bank',
            field=annoying.fields.JSONField(blank=True, default=[], deserializer=json.loads, null=True, serializer=annoying.fields.dumps),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='current_turn',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='game.GameTurn'),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='game.Game'),
        ),
        migrations.AddField(
            model_name='gameturn',
            name='pork_chop_used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
