# Generated by Django 3.1.13 on 2021-10-08 05:17

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0005_auto_20191128_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameDeck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deck_type', models.CharField(choices=[(100, 'Castle'), (101, 'Market'), (102, 'Villager')], max_length=10)),
                ('draw_pile', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('discard_pile', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
            ],
        ),
        migrations.AddConstraint(
            model_name='gamedeck',
            constraint=models.UniqueConstraint(fields=('game_id', 'deck_type'), name='unique deck per game'),
        ),
    ]
